### ISSUE TITLE
`mug.stl` asset

### ISSUE THREAD

**Issue by kamiradi** [Stanford-TML/SpringGrasp_release#1]
Hi,

Thanks for open sourcing your project. Where in your library can I find the following [mug](https://github.com/Stanford-TML/SpringGrasp_release/blob/4c644f669f61d635af5d25a1eea8994b62677b8a/gpis/gpis.py#L204) asset?

Thanks for your help

**Comment by Ericcsr** [comment]
This is the link to my original repository: https://github.com/Ericcsr/ComplianceDex/tree/main/assets
All missing assets can be found here. The code in this repository may be obsolete though.
